<?php

namespace Database\Seeders\Items;

use App\Models\Item;
use Illuminate\Database\Seeder;

class LootSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            // ========================================
            // Common Loot
            // ========================================
            [
                'name' => 'Stolen Watch',
                'slug' => 'stolen-watch',
                'description' => 'A basic wristwatch lifted from a distracted pedestrian',
                'type' => 'special',
                'subtype' => 'loot',
                'rarity' => 'common',
                'damage' => 0,
                'armor' => 0,
                'accuracy' => 0,
                'base_price' => 150,
                'market_price' => 200,
                'tradeable' => true,
                'consumable' => false,
                'level_required' => 1,
            ],
            [
                'name' => 'Cheap Phone',
                'slug' => 'cheap-phone',
                'description' => 'An old smartphone with a cracked screen',
                'type' => 'special',
                'subtype' => 'loot',
                'rarity' => 'common',
                'damage' => 0,
                'armor' => 0,
                'accuracy' => 0,
                'base_price' => 100,
                'market_price' => 150,
                'tradeable' => true,
                'consumable' => false,
                'level_required' => 1,
            ],
            [
                'name' => 'Wallet',
                'slug' => 'wallet',
                'description' => 'A leather wallet, empty of course',
                'type' => 'special',
                'subtype' => 'loot',
                'rarity' => 'common',
                'damage' => 0,
                'armor' => 0,
                'accuracy' => 0,
                'base_price' => 50,
                'market_price' => 75,
                'tradeable' => true,
                'consumable' => false,
                'level_required' => 1,
            ],
            [
                'name' => 'Cigarettes',
                'slug' => 'cigarettes',
                'description' => 'A pack of premium cigarettes',
                'type' => 'special',
                'subtype' => 'loot',
                'rarity' => 'common',
                'damage' => 0,
                'armor' => 0,
                'accuracy' => 0,
                'base_price' => 25,
                'market_price' => 40,
                'tradeable' => true,
                'consumable' => false,
                'level_required' => 1,
            ],
            [
                'name' => 'Sunglasses',
                'slug' => 'sunglasses',
                'description' => 'Designer shades, probably fake',
                'type' => 'special',
                'subtype' => 'loot',
                'rarity' => 'common',
                'damage' => 0,
                'armor' => 0,
                'accuracy' => 0,
                'base_price' => 75,
                'market_price' => 100,
                'tradeable' => true,
                'consumable' => false,
                'level_required' => 1,
            ],

            // ========================================
            // Uncommon Loot
            // ========================================
            [
                'name' => 'Gold Chain',
                'slug' => 'gold-chain',
                'description' => 'A flashy gold necklace',
                'type' => 'special',
                'subtype' => 'loot',
                'rarity' => 'uncommon',
                'damage' => 0,
                'armor' => 0,
                'accuracy' => 0,
                'base_price' => 500,
                'market_price' => 750,
                'tradeable' => true,
                'consumable' => false,
                'level_required' => 1,
            ],
            [
                'name' => 'Smartphone',
                'slug' => 'smartphone',
                'description' => 'A modern smartphone in good condition',
                'type' => 'special',
                'subtype' => 'loot',
                'rarity' => 'uncommon',
                'damage' => 0,
                'armor' => 0,
                'accuracy' => 0,
                'base_price' => 800,
                'market_price' => 1000,
                'tradeable' => true,
                'consumable' => false,
                'level_required' => 1,
            ],
            [
                'name' => 'Designer Handbag',
                'slug' => 'designer-handbag',
                'description' => 'A luxury handbag from a high-end boutique',
                'type' => 'special',
                'subtype' => 'loot',
                'rarity' => 'uncommon',
                'damage' => 0,
                'armor' => 0,
                'accuracy' => 0,
                'base_price' => 1200,
                'market_price' => 1500,
                'tradeable' => true,
                'consumable' => false,
                'level_required' => 1,
            ],
            [
                'name' => 'Laptop',
                'slug' => 'laptop',
                'description' => 'A used laptop, still works',
                'type' => 'special',
                'subtype' => 'loot',
                'rarity' => 'uncommon',
                'damage' => 0,
                'armor' => 0,
                'accuracy' => 0,
                'base_price' => 600,
                'market_price' => 850,
                'tradeable' => true,
                'consumable' => false,
                'level_required' => 1,
            ],
            [
                'name' => 'Car Stereo',
                'slug' => 'car-stereo',
                'description' => 'Ripped out of some nice car',
                'type' => 'special',
                'subtype' => 'loot',
                'rarity' => 'uncommon',
                'damage' => 0,
                'armor' => 0,
                'accuracy' => 0,
                'base_price' => 400,
                'market_price' => 550,
                'tradeable' => true,
                'consumable' => false,
                'level_required' => 1,
            ],

            // ========================================
            // Rare Loot
            // ========================================
            [
                'name' => 'Diamond Ring',
                'slug' => 'diamond-ring',
                'description' => 'A sparkling diamond engagement ring',
                'type' => 'special',
                'subtype' => 'loot',
                'rarity' => 'rare',
                'damage' => 0,
                'armor' => 0,
                'accuracy' => 0,
                'base_price' => 5000,
                'market_price' => 7500,
                'tradeable' => true,
                'consumable' => false,
                'level_required' => 1,
            ],
            [
                'name' => 'Rolex Watch',
                'slug' => 'rolex-watch',
                'description' => 'A genuine luxury timepiece',
                'type' => 'special',
                'subtype' => 'loot',
                'rarity' => 'rare',
                'damage' => 0,
                'armor' => 0,
                'accuracy' => 0,
                'base_price' => 8000,
                'market_price' => 12000,
                'tradeable' => true,
                'consumable' => false,
                'level_required' => 1,
            ],
            [
                'name' => 'Cash Stack',
                'slug' => 'cash-stack',
                'description' => 'A bundle of crisp bills',
                'type' => 'special',
                'subtype' => 'loot',
                'rarity' => 'rare',
                'damage' => 0,
                'armor' => 0,
                'accuracy' => 0,
                'base_price' => 3000,
                'market_price' => 3000,
                'tradeable' => true,
                'consumable' => false,
                'level_required' => 1,
            ],
            [
                'name' => 'Jewelry Box',
                'slug' => 'jewelry-box',
                'description' => 'A box full of assorted jewelry',
                'type' => 'special',
                'subtype' => 'loot',
                'rarity' => 'rare',
                'damage' => 0,
                'armor' => 0,
                'accuracy' => 0,
                'base_price' => 4500,
                'market_price' => 6000,
                'tradeable' => true,
                'consumable' => false,
                'level_required' => 1,
            ],
            [
                'name' => 'Safe Contents',
                'slug' => 'safe-contents',
                'description' => 'Whatever was in that safe',
                'type' => 'special',
                'subtype' => 'loot',
                'rarity' => 'rare',
                'damage' => 0,
                'armor' => 0,
                'accuracy' => 0,
                'base_price' => 10000,
                'market_price' => 15000,
                'tradeable' => true,
                'consumable' => false,
                'level_required' => 1,
            ],

            // ========================================
            // Epic Loot
            // ========================================
            [
                'name' => 'Gold Bars',
                'slug' => 'gold-bars',
                'description' => 'Pure gold bullion from a vault',
                'type' => 'special',
                'subtype' => 'loot',
                'rarity' => 'epic',
                'damage' => 0,
                'armor' => 0,
                'accuracy' => 0,
                'base_price' => 25000,
                'market_price' => 35000,
                'tradeable' => true,
                'consumable' => false,
                'level_required' => 1,
            ],
            [
                'name' => 'Rare Painting',
                'slug' => 'rare-painting',
                'description' => 'A valuable piece of stolen art',
                'type' => 'special',
                'subtype' => 'loot',
                'rarity' => 'epic',
                'damage' => 0,
                'armor' => 0,
                'accuracy' => 0,
                'base_price' => 50000,
                'market_price' => 75000,
                'tradeable' => true,
                'consumable' => false,
                'level_required' => 1,
            ],
            [
                'name' => 'Briefcase of Diamonds',
                'slug' => 'briefcase-diamonds',
                'description' => 'A case full of uncut diamonds',
                'type' => 'special',
                'subtype' => 'loot',
                'rarity' => 'epic',
                'damage' => 0,
                'armor' => 0,
                'accuracy' => 0,
                'base_price' => 75000,
                'market_price' => 100000,
                'tradeable' => true,
                'consumable' => false,
                'level_required' => 1,
            ],

            // ========================================
            // Legendary Loot
            // ========================================
            [
                'name' => 'Crown Jewels',
                'slug' => 'crown-jewels',
                'description' => 'Priceless royal artifacts',
                'type' => 'special',
                'subtype' => 'loot',
                'rarity' => 'legendary',
                'damage' => 0,
                'armor' => 0,
                'accuracy' => 0,
                'base_price' => 250000,
                'market_price' => 400000,
                'tradeable' => true,
                'consumable' => false,
                'level_required' => 1,
            ],
            [
                'name' => 'Black Market Data',
                'slug' => 'black-market-data',
                'description' => 'Encrypted data worth millions to the right buyer',
                'type' => 'special',
                'subtype' => 'loot',
                'rarity' => 'legendary',
                'damage' => 0,
                'armor' => 0,
                'accuracy' => 0,
                'base_price' => 500000,
                'market_price' => 750000,
                'tradeable' => true,
                'consumable' => false,
                'level_required' => 1,
            ],
        ];

        foreach ($items as $item) {
            Item::updateOrCreate(
                ['slug' => $item['slug']],
                $item
            );
        }
    }
}
